### PR TITLE
Update gedaq

### PR DESCRIPTION
**Pull request by SoftStoneDevelop**
Updated the Gedaq generator to the latest version. Also added some more accurate (given its capabilities) usage examples.

"https://github.com/ignatandrei/RSCG_Examples/tree/main/v2/book" - I'm not sure exactly how it is updated and where it is used. So I haven't changed anything there.

Getting the generator to work didn't work for me, even if I changed the absolute paths to my own (where my repository is).
But when building the site everything is fine - it works as it should. My version of the page is a bit different, is this acceptable or do I need to generate a sample page only through the generator?

### CODE REVIEW

**Comment by SoftStoneDevelop** [comment]
I'm also not sure what video.md is for or if it makes any sense for Gedaq.

**Comment by ignatandrei** [comment]
The video.md is  a json file ( sorry for that ) that tries to prepare transcript for recording a video .

**Comment by ignatandrei** [comment]
The file 

<RSCG_Examples>\v2\rscg_examples\Gedaq\readme.txt

is taken automatically from the Github


<RSCG_Examples>\v2\rscg_examples\Gedaq\nuget.txt


Both are compiled to the site , after building with Github Actions

**Comment by ignatandrei** [comment]
Please see now https://ignatandrei.github.io/RSCG_Examples/v2/docs/Gedaq

**Pull request merged**
